gg.jte.development-mode=true
spring.application.name=NBH

spring.mvc.hiddenmethod.filter.enabled=true

#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.url=jdbc:postgresql://nas.internal:5555/postgres
spring.datasource.username=postgres
spring.datasource.password=keines


logging.level.org.springframework.jdc=DEBUG
logging.level.eu.nabahilfe=DEBUG

logging.level.org.springframework.web.servlet=WARN

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.order_by.default_null_ordering=last
spring.jpa.properties.hibernate.transaction.jta.platform=enabled

server.port=8080


spring.mail.host=mail.your-server.de
spring.mail.port=587
spring.mail.username=${PROD_MAIL_USERNAME:}
spring.mail.password=${PROD_MAIL_PASSWORD:}

spring.mail.protocol=smtp
spring.mail.default-encoding=UTF-8

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=mail.your-server.de


spring.mail.properties.mail.debug=true
logging.level.org.eclipse.angus.mail=DEBUG

