gg:
    jte:
        "development-mode": true
        "use-precompiled-templates": false

spring:
    application:
        name: NBH

    mvc:
        hiddenmethod:
            filter:
                enabled: true

    datasource:
        url: jdbc:postgresql://nas.internal:5555/postgres
        username: "${POSTGRES_USERNAME}"
        password: "${POSTGRES_PASSWORD}"

    jpa:
        show-sql: false
        properties:
            hibernate:
                format_sql: false
                order_by:
                    default_null_ordering: last
                transaction:
                    jta:
                        platform: enabled

    mail:
        host: mail.your-server.de
        port: 587
        username: "${PROD_MAIL_USERNAME}"
        password: "${PROD_MAIL_PASSWORD}"
        protocol: smtp
        default-encoding: "UTF-8"
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        required: true
                    ssl:
                        trust: mail.your-server.de
                debug: true

logging:
    level:
        org.springframework.jdc: DEBUG
        eu.nabahilfe: DEBUG
        org.springframework.web.servlet: WARN
        org.eclipse.angus.mail: DEBUG

server:
    port: 8080
    servlet:
      session:
          timeout: 30m
          cookie:
              # for development
              secure: false
              # for production
              #secure: true
              #http-only: true
              #same-site: lax


app:
    base-url: http://localhost:8080

