gg:
    jte:
        # development-mode: true
        development-mode: false
        use-precompiled-templates: true

spring:
    application:
        name: NBH

    mvc:
        hiddenmethod:
            filter:
                enabled: true

    datasource:
        url: jdbc:postgresql://${DATABASE_URL}
        username: ${PGUSER}
        password: ${PGPASSWORD}

    jpa:
        show-sql: false
        open-in-view: true
        properties:
            hibernate:
                format_sql: false
                order_by:
                    default_null_ordering: last
                transaction:
                    jta:
                        platform: enabled

    mail:
        host: ${MAIL_HOST}
        port: ${MAIL_PORT}
        username: ${PROD_MAIL_USERNAME}
        password: ${PROD_MAIL_PASSWORD}
        protocol: smtp
        default-encoding: UTF-8
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        required: true
                    ssl:
                        trust: mail.your-server.de
                    # debug: true
                    debug: false

logging:
    level:
        org.springframework.jdc: DEBUG
        eu.nabahilfe: INFO
        org.springframework.web.servlet: WARN
        org.eclipse.angus.mail: DEBUG

server:
    # for railway deployment, use the PORT environment variable, otherwise default to 8080
    port: ${PORT:8080}
    forward-headers-strategy: framework
    servlet:
        session:
            timeout: 30m
            cookie:
                # for development
                secure: false
                # for production
                # secure: true
                http-only: true
                same-site: lax

app:
    base-url: ${APP_BASE_URL}

